# Generated by Django 5.2.7 on 2025-10-25 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Streamplatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('about', models.CharField(max_length=40)),
                ('website', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('plot', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('Availabe_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchlist.streamplatform')),
            ],
        ),
    ]
