# Generated by Django 5.2.7 on 2025-10-27 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0002_alter_watchlist_availabe_on_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='Availabe_on',
            new_name='watchlist',
        ),
    ]
