# Generated by Django 5.2.7 on 2025-10-29 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0004_reviews_review_user_alter_streamplatform_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='review',
        ),
        migrations.AddField(
            model_name='reviews',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='watchlist.watchlist'),
            preserve_default=False,
        ),
    ]
